# static-web-hosting
name: "preflight-configuration"
description: "configures AWS secrets"
inputs:
  role-to-assume:
    required: true
    description: AWS role to assume to STS creds generation.
runs:
  using: "composite"
  steps:
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: us-east-1